# Generated by Django 4.2 on 2023-04-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweetID', models.BigIntegerField()),
                ('tweet', models.CharField(max_length=500)),
                ('publishDateTime', models.DateTimeField()),
                ('lastUpdateDateTime', models.DateTimeField(blank=True, default=None, null=True)),
                ('mainHighway', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('geoname', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('score', models.FloatField(default=1)),
            ],
        ),
    ]
