# Generated by Django 4.2 on 2023-04-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='account',
            field=models.CharField(default='@511Alberta', max_length=20),
        ),
        migrations.AddField(
            model_name='tweet',
            name='province',
            field=models.CharField(default='AB', max_length=30),
        ),
    ]
